"""
PropFlow Configuration
Environment-specific settings for Qwen, Mem0, and Alibaba Cloud OSS
"""

from pydantic_settings import BaseSettings
from functools import lru_cache


class PropFlowSettings(BaseSettings):
    """PropFlow AI Agent Settings — loaded from server/.env"""

    # ── LLM Provider Selection (Phase B — configurable LLM layer) ────────────
    # Which provider backs ALL LLM calls (PropFlow chat agent + agreement AI).
    # Switch models by changing this ONE line — no code edits required.
    #   "qwen"   -> Alibaba DashScope (QWEN_* vars)          [default]
    #   "groq"   -> Groq Cloud llama family (GROQ_* vars)
    #   "openai" -> OpenAI (OPENAI_* vars)
    #   "mock"   -> offline; every call falls to deterministic mocks
    # See app/propflow/services/llm_provider.py for the plugin registry.
    LLM_PROVIDER: str = "qwen"

    # ── Qwen API (Alibaba Cloud DashScope) ───────────────────────────────────
    QWEN_API_KEY: str | None = None
    QWEN_API_URL: str = "https://dashscope-intl.aliyuncs.com/compatible-mode/v1"
    # Primary model: qwen-plus gives better structured output than qwen-turbo
    # for intent extraction; falls back to qwen-turbo if quota exceeded
    QWEN_MODEL: str = "qwen-plus"
    QWEN_FALLBACK_MODEL: str = "qwen-turbo"
    QWEN_TEMPERATURE: float = 0.1   # Low = deterministic, good for JSON extraction
    QWEN_MAX_TOKENS: int = 1000
    # TLS verification for the DashScope connection. Default True (secure).
    # Set QWEN_VERIFY_SSL=false in local .env ONLY if your dev machine's CA
    # store rejects DashScope's cert chain (Python 3.14 / OpenSSL strict X.509).
    # Production should keep this True.
    QWEN_VERIFY_SSL: bool = True

    # ── Groq API (used when LLM_PROVIDER=groq) ───────────────────────────────
    # Groq exposes an OpenAI-compatible endpoint, so the provider layer reuses
    # the same client. GROQ_API_KEY also serves the legacy /api/v1/groq routes.
    GROQ_API_KEY: str | None = None
    GROQ_API_URL: str = "https://api.groq.com/openai/v1"
    GROQ_MODEL: str = "llama-3.3-70b-versatile"
    GROQ_FALLBACK_MODEL: str | None = "llama-3.1-8b-instant"
    GROQ_TEMPERATURE: float = 0.1
    GROQ_MAX_TOKENS: int = 2500

    # ── OpenAI API (used when LLM_PROVIDER=openai) ───────────────────────────
    OPENAI_API_KEY: str | None = None
    OPENAI_API_URL: str = "https://api.openai.com/v1"
    OPENAI_MODEL: str = "gpt-4o-mini"
    OPENAI_FALLBACK_MODEL: str | None = None
    OPENAI_TEMPERATURE: float = 0.1
    OPENAI_MAX_TOKENS: int = 1000

    # ── Confidence Thresholds ─────────────────────────────────────────────────
    INTENT_CONFIDENCE_THRESHOLD: float = 0.7   # Below this, ask tenant to clarify
    PROPERTY_MATCH_THRESHOLD: float = 0.8

    # ── Mem0 Persistent Memory ────────────────────────────────────────────────
    # Use "local" for hackathon demo (no extra account needed)
    # Switch to "cloud" + MEM0_API_KEY for production
    MEM0_MODE: str = "local"        # "local" | "cloud"
    MEM0_API_KEY: str | None = None  # Only needed when MEM0_MODE=cloud
    # Local mode uses in-process vector store; no external service required
    MEM0_LOCAL_PATH: str = ".mem0_store"  # relative to server/ working dir

    # ── Agreement PDF Storage (Supabase Storage) ─────────────────────────────
    # Draft agreement PDFs generated by PropFlow are stored in the existing
    # `ownership-docs` bucket (public) under agreements/{id}/..., mirroring
    # the signed-PDF generator in app/routes/agreements.py. No new bucket or
    # external cloud account is required — Supabase creds are already in use
    # across the platform.
    AGREEMENT_STORAGE_BUCKET: str = "ownership-docs"

    # ── State Machine Configuration ───────────────────────────────────────────
    MAX_RETRIES: int = 3
    TIMEOUT_SECONDS: int = 30

    # ── Feature Flags ─────────────────────────────────────────────────────────
    ENABLE_PROPFLOW: bool = True
    ENABLE_MEM0_MEMORY: bool = False          # Toggle off in tests - disabled due to chromadb requirement
    ENABLE_NOMBA_INTEGRATION: bool = True
    ENABLE_LANDLORD_APPROVAL_INTERRUPT: bool = True
    ENABLE_TENANT_SIGN_INTERRUPT: bool = True

    class Config:
        env_file = ".env"
        case_sensitive = True
        extra = "ignore"


@lru_cache()
def get_propflow_settings() -> PropFlowSettings:
    return PropFlowSettings()


propflow_settings = get_propflow_settings()
