"""
Script to create 25 sample properties for landlord jaydam@gmail.com
"""
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.database import supabase_admin
from datetime import datetime, date
import json

# Sample property data with diverse images and details
properties_data = [
    {
        "title": "Modern 3-Bedroom Apartment in Lekki Phase 1",
        "description": "Spacious and modern apartment with excellent finishing, 24/7 security, and proximity to shopping centers. Perfect for families looking for comfort and convenience.",
        "rent_amount": 850000,
        "security_deposit": 850000,
        "location": "Lekki Phase 1",
        "address": "23 Admiralty Way, Lekki Phase 1",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.4613,
        "longitude": 3.5404,
        "bedrooms": 3,
        "bathrooms": 2,
        "square_feet": 1200,
        "property_type": "apartment",
        "amenities": ["Air Conditioning", "Security", "Parking", "Swimming Pool", "Gym", "Backup Power"],
        "photos": ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop"],
        "status": "vacant"
    },
    {
        "title": "Luxury 2-Bedroom Duplex in Victoria Island",
        "description": "Elegant duplex with premium finishes, sea view, and modern amenities. Located in the heart of Victoria Island with easy access to business districts.",
        "rent_amount": 1200000,
        "security_deposit": 1200000,
        "location": "Victoria Island",
        "address": "45 Ahmadu Bello Way, Victoria Island",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.4281,
        "longitude": 3.4215,
        "bedrooms": 2,
        "bathrooms": 2,
        "square_feet": 950,
        "property_type": "duplex",
        "amenities": ["Air Conditioning", "Security", "Parking", "Swimming Pool", "Gym", "Elevator", "Sea View"],
        "photos": ["https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&h=600&fit=crop"],
        "status": "vacant"
    },
    {
        "title": "Cozy 1-Bedroom Studio in Ikoyi",
        "description": "Compact and stylish studio perfect for young professionals. Fully furnished with modern appliances and excellent security.",
        "rent_amount": 450000,
        "security_deposit": 450000,
        "location": "Ikoyi",
        "address": "12 Awolowo Road, Ikoyi",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.4531,
        "longitude": 3.4253,
        "bedrooms": 1,
        "bathrooms": 1,
        "square_feet": 600,
        "property_type": "studio",
        "amenities": ["Air Conditioning", "Security", "Parking", "Gym", "Fully Furnished"],
        "photos": ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop"],
                "status": "vacant"
    },
    {
        "title": "Spacious 4-Bedroom House in Ikeja GRA",
        "description": "Beautiful detached house with garden, perfect for large families. Located in the prestigious Ikeja GRA with excellent infrastructure.",
        "rent_amount": 1500000,
        "security_deposit": 1500000,
        "location": "Ikeja GRA",
        "address": "78 Obafemi Awolowo Way, Ikeja GRA",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.6018,
        "longitude": 3.3515,
        "bedrooms": 4,
        "bathrooms": 3,
        "square_feet": 2000,
        "property_type": "house",
        "amenities": ["Air Conditioning", "Security", "Parking", "Garden", "Backup Power", "Staff Quarters"],
        "photos": ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&h=600&fit=crop"],
        "availability_start": date(2026, 2, 1),
        "status": "vacant"
    },
    {
        "title": "Penthouse Suite in Eko Atlantic",
        "description": "Ultra-luxury penthouse with panoramic ocean views, private elevator, and world-class amenities. Experience the pinnacle of luxury living.",
        "rent_amount": 3500000,
        "security_deposit": 3500000,
        "location": "Eko Atlantic",
        "address": "Ocean View Towers, Eko Atlantic",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.4167,
        "longitude": 3.4167,
        "bedrooms": 5,
        "bathrooms": 4,
        "square_feet": 3500,
        "property_type": "penthouse",
        "amenities": ["Air Conditioning", "Security", "Parking", "Swimming Pool", "Gym", "Ocean View", "Private Elevator", "Concierge"],
        "photos": ["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=600&fit=crop"],
        "availability_start": date(2026, 1, 25),
        "status": "vacant"
    },
    {
        "title": "Modern 2-Bedroom Flat in Yaba",
        "description": "Contemporary apartment near universities and tech hubs. Ideal for students and young professionals with easy access to public transport.",
        "rent_amount": 380000,
        "security_deposit": 380000,
        "location": "Yaba",
        "address": "45 Herbert Macaulay Way, Yaba",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.5244,
        "longitude": 3.3792,
        "bedrooms": 2,
        "bathrooms": 1,
        "square_feet": 750,
        "property_type": "apartment",
        "amenities": ["Air Conditioning", "Security", "Parking", "Backup Power"],
        "photos": ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop"],
        "availability_start": date(2026, 1, 18),
        "status": "vacant"
    },
    {
        "title": "3-Bedroom Townhouse in Lekki Phase 2",
        "description": "Modern townhouse with private garden and community amenities. Perfect for families seeking a balanced lifestyle in a serene environment.",
        "rent_amount": 950000,
        "security_deposit": 950000,
        "location": "Lekki Phase 2",
        "address": "15 Freedom Way, Lekki Phase 2",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.4418,
        "longitude": 3.5553,
        "bedrooms": 3,
        "bathrooms": 2,
        "square_feet": 1400,
        "property_type": "house",
        "amenities": ["Air Conditioning", "Security", "Parking", "Garden", "Community Pool", "Playground"],
        "photos": ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop"],
        "availability_start": date(2026, 1, 22),
        "status": "vacant"
    },
    {
        "title": "Executive 1-Bedroom in Banana Island",
        "description": "Premium apartment in Nigeria's most exclusive neighborhood. Luxury finishes, private beach access, and world-class security.",
        "rent_amount": 1800000,
        "security_deposit": 1800000,
        "location": "Banana Island",
        "address": "8 Banana Island Road, Ikoyi",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.4531,
        "longitude": 3.4253,
        "bedrooms": 1,
        "bathrooms": 1,
        "square_feet": 800,
        "property_type": "apartment",
        "amenities": ["Air Conditioning", "Security", "Parking", "Beach Access", "Gym", "Concierge", "Private Garden"],
        "photos": ["https://images.unsplash.com/photo-1445019980578-5996b9c8272e?w=800&h=600&fit=crop"],
        "availability_start": date(2026, 2, 5),
        "status": "vacant"
    },
    {
        "title": "Budget 2-Bedroom in Surulere",
        "description": "Affordable and well-maintained apartment in a central location. Close to markets, schools, and public transport. Great value for money.",
        "rent_amount": 320000,
        "security_deposit": 320000,
        "location": "Surulere",
        "address": "78 Bode Thomas Street, Surulere",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.5480,
        "longitude": 3.3517,
        "bedrooms": 2,
        "bathrooms": 1,
        "square_feet": 700,
        "property_type": "apartment",
        "amenities": ["Air Conditioning", "Security", "Parking"],
        "photos": ["https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&h=600&fit=crop"],
        "availability_start": date(2026, 1, 12),
        "status": "vacant"
    },
    {
        "title": "Luxury 3-Bedroom Duplex in Ajah",
        "description": "Spacious duplex with modern architecture and premium finishes. Located in the rapidly developing Ajah corridor with excellent connectivity.",
        "rent_amount": 1100000,
        "security_deposit": 1100000,
        "location": "Ajah",
        "address": "124 Lekki-Epe Expressway, Ajah",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.4550,
        "longitude": 3.5650,
        "bedrooms": 3,
        "bathrooms": 3,
        "square_feet": 1600,
        "property_type": "duplex",
        "amenities": ["Air Conditioning", "Security", "Parking", "Swimming Pool", "Gym", "Backup Power", "Garden"],
        "photos": ["https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=800&h=600&fit=crop"],
        "availability_start": date(2026, 1, 28),
        "status": "vacant"
    },
    {
        "title": "Modern Studio in Maryland",
        "description": "Compact and efficient studio perfect for singles. Fully furnished with modern amenities and excellent security in a prime location.",
        "rent_amount": 280000,
        "security_deposit": 280000,
        "location": "Maryland",
        "address": "45 Ikorodu Road, Maryland",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.5600,
        "longitude": 3.3760,
        "bedrooms": 0,
        "bathrooms": 1,
        "square_feet": 450,
        "property_type": "studio",
        "amenities": ["Air Conditioning", "Security", "Parking", "Fully Furnished"],
        "photos": ["https://images.unsplash.com/photo-1502672260266-1c1a7bf8a2f0?w=800&h=600&fit=crop"],
        "availability_start": date(2026, 1, 15),
        "status": "vacant"
    },
    {
        "title": "4-Bedroom Maisonette in Gbagada",
        "description": "Spacious maisonette with multiple levels and private garden. Ideal for large families seeking space and comfort in a serene environment.",
        "rent_amount": 1300000,
        "security_deposit": 1300000,
        "location": "Gbagada",
        "address": "23 Gbagada Expressway, Gbagada",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.5800,
        "longitude": 3.3800,
        "bedrooms": 4,
        "bathrooms": 3,
        "square_feet": 2200,
        "property_type": "house",
        "amenities": ["Air Conditioning", "Security", "Parking", "Garden", "Backup Power", "Staff Quarters"],
        "photos": ["https://images.unsplash.com/photo-1416339134316-0e91dc9ded92?w=800&h=600&fit=crop"],
        "availability_start": date(2026, 2, 10),
        "status": "vacant"
    },
    {
        "title": "2-Bedroom Flat in Festac Town",
        "description": "Well-maintained apartment in a planned residential area. Close to markets, schools, and recreational facilities. Great community living.",
        "rent_amount": 350000,
        "security_deposit": 350000,
        "location": "Festac Town",
        "address": "123 Festac Town Road, Festac",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.4700,
        "longitude": 3.2800,
        "bedrooms": 2,
        "bathrooms": 1,
        "square_feet": 800,
        "property_type": "apartment",
        "amenities": ["Air Conditioning", "Security", "Parking", "Community Center"],
        "photos": ["https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop"],
        "availability_start": date(2026, 1, 20),
        "status": "vacant"
    },
    {
        "title": "Executive 3-Bedroom in Ikoyi",
        "description": "Premium apartment in one of Lagos' most prestigious neighborhoods. Luxury finishes, excellent security, and proximity to business districts.",
        "rent_amount": 2000000,
        "security_deposit": 2000000,
        "location": "Ikoyi",
        "address": "67 Ikoyi Club Road, Ikoyi",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.4531,
        "longitude": 3.4253,
        "bedrooms": 3,
        "bathrooms": 3,
        "square_feet": 1800,
        "property_type": "apartment",
        "amenities": ["Air Conditioning", "Security", "Parking", "Swimming Pool", "Gym", "Concierge", "Garden"],
        "photos": ["https://images.unsplash.com/photo-1582268611958-ebfd16135945?w=800&h=600&fit=crop"],
        "availability_start": date(2026, 2, 15),
        "status": "vacant"
    },
    {
        "title": "1-Bedroom Flat in Mushin",
        "description": "Affordable apartment in a central location with easy access to transportation and markets. Perfect for budget-conscious individuals.",
        "rent_amount": 220000,
        "security_deposit": 220000,
        "location": "Mushin",
        "address": "45 Mushin Road, Mushin",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.5400,
        "longitude": 3.3400,
        "bedrooms": 1,
        "bathrooms": 1,
        "square_feet": 550,
        "property_type": "apartment",
        "amenities": ["Air Conditioning", "Security"],
        "photos": ["https://images.unsplash.com/photo-1521788772331-1c028f6204d3?w=800&h=600&fit=crop"],
        "availability_start": date(2026, 1, 8),
        "status": "vacant"
    },
    {
        "title": "5-Bedroom Villa in Lekki",
        "description": "Luxurious villa with private pool, garden, and staff quarters. Ultimate privacy and security in an exclusive gated community.",
        "rent_amount": 2800000,
        "security_deposit": 2800000,
        "location": "Lekki",
        "address": "15 Lekki Peninsula Scheme 1, Lekki",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.4418,
        "longitude": 3.5553,
        "bedrooms": 5,
        "bathrooms": 4,
        "square_feet": 4000,
        "property_type": "house",
        "amenities": ["Air Conditioning", "Security", "Parking", "Swimming Pool", "Gym", "Garden", "Staff Quarters", "Private Cinema"],
        "photos": ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop"],
        "availability_start": date(2026, 2, 20),
        "status": "vacant"
    },
    {
        "title": "2-Bedroom Apartment in Apapa",
        "description": "Modern apartment near the port with excellent connectivity. Perfect for professionals working in the maritime and logistics sectors.",
        "rent_amount": 480000,
        "security_deposit": 480000,
        "location": "Apapa",
        "address": "78 Creek Road, Apapa",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.4500,
        "longitude": 3.3500,
        "bedrooms": 2,
        "bathrooms": 2,
        "square_feet": 850,
        "property_type": "apartment",
        "amenities": ["Air Conditioning", "Security", "Parking", "Backup Power", "Gym"],
        "photos": ["https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=800&h=600&fit=crop"],
        "availability_start": date(2026, 1, 25),
        "status": "vacant"
    },
    {
        "title": "3-Bedroom Flat in Oshodi",
        "description": "Spacious apartment in a bustling commercial area. Excellent for families with proximity to markets, schools, and transport hubs.",
        "rent_amount": 420000,
        "security_deposit": 420000,
        "location": "Oshodi",
        "address": "45 Oshodi Road, Oshodi",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.5500,
        "longitude": 3.3300,
        "bedrooms": 3,
        "bathrooms": 2,
        "square_feet": 1100,
        "property_type": "apartment",
        "amenities": ["Air Conditioning", "Security", "Parking", "Backup Power"],
        "photos": ["https://images.unsplash.com/photo-1600566753190-98b26bd0f849?w=800&h=600&fit=crop"],
        "availability_start": date(2026, 1, 30),
        "status": "vacant"
    },
    {
        "title": "Luxury Studio in Victoria Island",
        "description": "High-end studio with premium finishes and excellent amenities. Perfect for executives and young professionals in the heart of business district.",
        "rent_amount": 550000,
        "security_deposit": 550000,
        "location": "Victoria Island",
        "address": "89 Adeola Odeku Street, Victoria Island",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.4281,
        "longitude": 3.4215,
        "bedrooms": 0,
        "bathrooms": 1,
        "square_feet": 650,
        "property_type": "studio",
        "amenities": ["Air Conditioning", "Security", "Parking", "Gym", "Concierge", "Fully Furnished"],
        "photos": ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop"],
        "availability_start": date(2026, 2, 1),
        "status": "vacant"
    },
    {
        "title": "4-Bedroom Duplex in Magodo",
        "description": "Elegant duplex in a gated community with excellent security and amenities. Perfect for families seeking space and tranquility.",
        "rent_amount": 1450000,
        "security_deposit": 1450000,
        "location": "Magodo",
        "address": "15 Magodo GRA Road, Magodo",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.6100,
        "longitude": 3.3700,
        "bedrooms": 4,
        "bathrooms": 3,
        "square_feet": 2400,
        "property_type": "duplex",
        "amenities": ["Air Conditioning", "Security", "Parking", "Swimming Pool", "Gym", "Garden", "Backup Power"],
        "photos": ["https://images.unsplash.com/photo-1600047509807-ba8f800d6342?w=800&h=600&fit=crop"],
        "availability_start": date(2026, 2, 5),
        "status": "vacant"
    },
    {
        "title": "1-Bedroom in Ketu",
        "description": "Affordable and well-located apartment with easy access to mainland and island. Perfect for young professionals and couples.",
        "rent_amount": 260000,
        "security_deposit": 260000,
        "location": "Ketu",
        "address": "34 Ketu Road, Ketu",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.5900,
        "longitude": 3.3800,
        "bedrooms": 1,
        "bathrooms": 1,
        "square_feet": 500,
        "property_type": "apartment",
        "amenities": ["Air Conditioning", "Security", "Parking"],
        "photos": ["https://images.unsplash.com/photo-1600585154526-990dced4db0b?w=800&h=600&fit=crop"],
        "availability_start": date(2026, 1, 18),
        "status": "vacant"
    },
    {
        "title": "3-Bedroom House in Anthony Village",
        "description": "Spacious house in a quiet residential area. Perfect for families with proximity to schools, markets, and healthcare facilities.",
        "rent_amount": 780000,
        "security_deposit": 780000,
        "location": "Anthony Village",
        "address": "67 Anthony Village Road, Anthony",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.5700,
        "longitude": 3.3700,
        "bedrooms": 3,
        "bathrooms": 2,
        "square_feet": 1500,
        "property_type": "house",
        "amenities": ["Air Conditioning", "Security", "Parking", "Garden", "Backup Power"],
        "photos": ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop"],
        "availability_start": date(2026, 1, 27),
        "status": "vacant"
    },
    {
        "title": "2-Bedroom in Ilupeju",
        "description": "Modern apartment in an industrial-commercial area. Ideal for professionals working in nearby companies with excellent connectivity.",
        "rent_amount": 410000,
        "security_deposit": 410000,
        "location": "Ilupeju",
        "address": "23 Ilupeju Industrial Road, Ilupeju",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.5600,
        "longitude": 3.3600,
        "bedrooms": 2,
        "bathrooms": 1,
        "square_feet": 780,
        "property_type": "apartment",
        "amenities": ["Air Conditioning", "Security", "Parking", "Backup Power"],
        "photos": ["https://images.unsplash.com/photo-1600607687644-c8175b97f2be?w=800&h=600&fit=crop"],
        "availability_start": date(2026, 2, 8),
        "status": "vacant"
    },
    {
        "title": "Executive Penthouse in Victoria Island",
        "description": "Ultra-luxury penthouse with 360-degree city views, private pool, and world-class amenities. The epitome of luxury living in Lagos.",
        "rent_amount": 4200000,
        "security_deposit": 4200000,
        "location": "Victoria Island",
        "address": "1001 Towers, Victoria Island",
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "latitude": 6.4281,
        "longitude": 3.4215,
        "bedrooms": 6,
        "bathrooms": 5,
        "square_feet": 5000,
        "property_type": "penthouse",
        "amenities": ["Air Conditioning", "Security", "Parking", "Swimming Pool", "Gym", "City View", "Private Elevator", "Concierge", "Private Cinema", "Wine Cellar"],
        "photos": ["https://images.unsplash.com/photo-1600566753190-98b26bd0f849?w=800&h=600&fit=crop"],
        "availability_start": date(2026, 3, 1),
        "status": "vacant"
    }
]

def create_properties():
    """Create 25 properties for landlord jaydam@gmail.com"""
    landlord_id = "8e7992b4-e136-44a0-aa2c-271c3a653736"
    
    print(f"Creating {len(properties_data)} properties for landlord {landlord_id}...")
    
    success_count = 0
    error_count = 0
    
    for i, prop_data in enumerate(properties_data, 1):
        try:
            # Add landlord_id and timestamps
            property_data = {
                "landlord_id": landlord_id,
                "created_at": datetime.now().isoformat(),
                "updated_at": datetime.now().isoformat(),
                "view_count": 0,
                **prop_data
            }
            
            print(f"\n📝 Creating property {i}: {prop_data['title']}")
            
            # Insert property
            result = supabase_admin.table("properties").insert(property_data).execute()
            
            if result.data and len(result.data) > 0:
                created_property = result.data[0]
                print(f"✅ Property created successfully with ID: {created_property.get('id')}")
                success_count += 1
            else:
                print(f"❌ Failed to create property - no data returned")
                error_count += 1
                
        except Exception as e:
            print(f"❌ Error creating property {i}: {str(e)}")
            error_count += 1
    
    print(f"\n📊 Summary:")
    print(f"✅ Successfully created: {success_count} properties")
    print(f"❌ Failed to create: {error_count} properties")
    print(f"📈 Total processed: {success_count + error_count} properties")

if __name__ == "__main__":
    create_properties()
