-- Create licenses table for NuloAfrica license tracking
-- Stores app license expiry and management info

CREATE TABLE IF NOT EXISTS licenses (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    license_key TEXT UNIQUE NOT NULL DEFAULT 'nulo_main_license',
    expiry_date TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    extended_count INT NOT NULL DEFAULT 0,
    last_extended_at TIMESTAMP WITH TIME ZONE,
    notes TEXT,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_licenses_key ON licenses(license_key);
CREATE INDEX IF NOT EXISTS idx_licenses_expiry ON licenses(expiry_date);

-- Disable RLS for licenses table (application-level control)
-- Since license is application-wide, not user-specific
ALTER TABLE licenses DISABLE ROW LEVEL SECURITY;

-- Insert initial license record if not exists
INSERT INTO licenses (license_key, expiry_date, created_at, extended_count, notes)
VALUES (
    'nulo_main_license',
    NOW() + INTERVAL '90 days',
    NOW(),
    0,
    'Initial 90-day protection period for NuloAfrica app'
)
ON CONFLICT (license_key) DO NOTHING;

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_licenses_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_licenses_updated_at ON licenses;
CREATE TRIGGER trigger_licenses_updated_at
    BEFORE UPDATE ON licenses
    FOR EACH ROW
    EXECUTE FUNCTION update_licenses_updated_at();
