"""
PropFlow Alibaba Cloud OSS Service
Stores generated tenancy agreement PDFs in Alibaba Cloud Object Storage.

HACKATHON NOTE:
  This file is the mandatory "proof of Alibaba Cloud service usage" required
  by the hackathon submission. Point judges to this file.
  Endpoint: https://oss-ap-southeast-1.aliyuncs.com
  Bucket:   nuloafrica-agreements (created in Alibaba Cloud console)

Architecture:
  - Agreement PDFs generated by Groq (existing) are stored here instead of
    (or in addition to) Supabase Storage.
  - Each file is stored under: agreements/{agreement_id}/lease_{timestamp}.pdf
  - A signed URL (valid 1 hour) is returned to show the tenant/landlord the PDF.
  - The OSS key is written back to PropFlowState.agreement_pdf_oss_key so the
    resume endpoint can include the download link in notifications.

Graceful degradation:
  - If oss2 is not installed or creds not set, upload() returns None and logs a
    warning. The workflow continues — PDF just won't be in OSS.
"""

import logging
import io
from datetime import datetime
from typing import Optional
from app.propflow.config import propflow_settings

logger = logging.getLogger(__name__)

# Signed URL expiry: 3600 seconds (1 hour) — same as Supabase pattern in ARCHITECTURE.md
_SIGNED_URL_EXPIRY = 3600


def _build_oss_bucket():
    """
    Build the OSS Bucket client. Returns None if oss2 not installed or creds missing.
    """
    if not propflow_settings.ENABLE_OSS_STORAGE:
        logger.info("OSS storage disabled via ENABLE_OSS_STORAGE=False")
        return None

    if not (
        propflow_settings.ALIBABA_CLOUD_ACCESS_KEY_ID
        and propflow_settings.ALIBABA_CLOUD_ACCESS_KEY_SECRET
    ):
        logger.warning(
            "ALIBABA_CLOUD_ACCESS_KEY_ID / SECRET not set. "
            "OSS uploads will be skipped. Set these in .env to enable."
        )
        return None

    try:
        import oss2
    except ImportError:
        logger.warning("oss2 not installed. Run: pip install oss2>=2.18.0")
        return None

    auth = oss2.Auth(
        propflow_settings.ALIBABA_CLOUD_ACCESS_KEY_ID,
        propflow_settings.ALIBABA_CLOUD_ACCESS_KEY_SECRET,
    )
    bucket = oss2.Bucket(
        auth,
        propflow_settings.OSS_ENDPOINT,
        propflow_settings.OSS_BUCKET_NAME,
    )
    logger.info(
        f"Alibaba Cloud OSS initialised: "
        f"bucket={propflow_settings.OSS_BUCKET_NAME} "
        f"endpoint={propflow_settings.OSS_ENDPOINT}"
    )
    return bucket


class OSSClient:
    """
    Client for storing and retrieving agreement PDFs on Alibaba Cloud OSS.
    """

    def __init__(self):
        self._bucket = _build_oss_bucket()
        self._available = self._bucket is not None

    @property
    def available(self) -> bool:
        return self._available

    def upload_agreement_pdf(
        self,
        agreement_id: str,
        pdf_bytes: bytes,
    ) -> Optional[str]:
        """
        Upload a tenancy agreement PDF to OSS.

        Args:
            agreement_id: UUID string of the agreement (used as path prefix)
            pdf_bytes:    Raw PDF bytes from the agreement generator

        Returns:
            OSS object key on success (e.g. "agreements/uuid/lease_20260715.pdf")
            None if OSS unavailable or upload failed
        """
        if not self._available:
            logger.info("OSS not available — skipping PDF upload (workflow continues)")
            return None

        timestamp = datetime.utcnow().strftime("%Y%m%dT%H%M%S")
        oss_key = f"agreements/{agreement_id}/lease_{timestamp}.pdf"

        try:
            self._bucket.put_object(
                oss_key,
                io.BytesIO(pdf_bytes),
                headers={"Content-Type": "application/pdf"},
            )
            logger.info(f"OSS upload success: key={oss_key} size={len(pdf_bytes)} bytes")
            return oss_key
        except Exception as exc:
            logger.error(f"OSS upload failed for agreement {agreement_id}: {exc}")
            return None

    def get_signed_url(self, oss_key: str, expiry_seconds: int = _SIGNED_URL_EXPIRY) -> Optional[str]:
        """
        Generate a signed (time-limited) download URL for a stored agreement PDF.

        The 1-hour expiry matches the Supabase signed URL pattern used elsewhere
        in the platform (see ARCHITECTURE.md §4.5 PII handling).

        Args:
            oss_key:        The key returned by upload_agreement_pdf()
            expiry_seconds: How long the URL is valid (default 3600s)

        Returns:
            Signed HTTPS URL string, or None if OSS unavailable
        """
        if not self._available:
            return None

        try:
            import oss2
            url = self._bucket.sign_url("GET", oss_key, expiry_seconds)
            logger.info(f"OSS signed URL generated: key={oss_key} expiry={expiry_seconds}s")
            return url
        except Exception as exc:
            logger.error(f"OSS sign_url failed for key {oss_key}: {exc}")
            return None

    def delete_agreement_pdf(self, oss_key: str) -> bool:
        """
        Delete a stored agreement PDF (e.g. when agreement is withdrawn).

        Returns True on success, False on failure.
        """
        if not self._available:
            return False

        try:
            self._bucket.delete_object(oss_key)
            logger.info(f"OSS delete success: key={oss_key}")
            return True
        except Exception as exc:
            logger.error(f"OSS delete failed for key {oss_key}: {exc}")
            return False


# Singleton — same pattern as qwen_client.py and mem0_client.py
oss_client = OSSClient()
