"""
PropFlow Supabase Storage Service
Stores generated tenancy agreement draft PDFs in Supabase Storage, reusing
the existing `ownership-docs` bucket (same bucket + path convention used by
the signed-PDF generator in app/routes/agreements.py).

Architecture:
  - Agreement draft PDFs generated by PropFlow's create_agreement node are
    stored under: agreements/{agreement_id}/lease_{timestamp}.pdf
  - `ownership-docs` is a PUBLIC bucket, so a permanent public URL is
    returned via get_public_url() (no signed-URL expiry to manage).
  - The storage path is written back to PropFlowState.agreement_pdf_storage_key
    and the public URL to agreement_pdf_url so the resume endpoint can include
    the download link in notifications / responses.

Graceful degradation:
  - If Supabase Storage is unavailable or the upload fails, upload_agreement_pdf()
    returns None and logs a warning. The workflow continues — the PDF just won't
    be stored. This mirrors the previous OSS behaviour (non-fatal).
"""

import logging
import uuid
from datetime import datetime, timezone
from typing import Optional

from app.database import supabase_admin, run_db_async
from app.propflow.config import propflow_settings

logger = logging.getLogger(__name__)


class SupabaseStorageClient:
    """
    Client for storing and retrieving agreement PDFs in Supabase Storage.
    """

    def __init__(self, bucket: Optional[str] = None):
        self._bucket = bucket or propflow_settings.AGREEMENT_STORAGE_BUCKET

    async def upload_agreement_pdf(
        self,
        agreement_id: str,
        pdf_bytes: bytes,
    ) -> Optional[str]:
        """
        Upload a tenancy agreement draft PDF to Supabase Storage.

        Args:
            agreement_id: UUID string of the agreement (used as path prefix)
            pdf_bytes:    Raw PDF bytes generated by the agreement node

        Returns:
            Storage object path on success (e.g. "agreements/uuid/lease_....pdf")
            None if the upload fails (workflow continues).
        """
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S")
        # A UUID suffix avoids clobbering an existing object in the public
        # bucket, so the download URL never points at a stale/cached copy.
        path = f"agreements/{agreement_id}/lease_{timestamp}_{uuid.uuid4().hex[:8]}.pdf"

        try:

            def _do_upload():
                return (
                    supabase_admin.storage.from_(self._bucket)
                    .upload(
                        file=pdf_bytes,
                        path=path,
                        file_options={"content-type": "application/pdf"},
                    )
                )

            # run_db_async is a coroutine that offloads the blocking supabase-py
            # call to the thread pool — it MUST be awaited or the upload never runs.
            await run_db_async(_do_upload)
            logger.info(
                f"[propflow] PDF uploaded to {self._bucket}/{path} "
                f"size={len(pdf_bytes)} bytes"
            )
            return path
        except Exception as exc:
            logger.error(
                f"[propflow] Supabase upload failed for agreement {agreement_id}: {exc}"
            )
            return None

    def get_download_url(self, path: str) -> Optional[str]:
        """
        Return a public download URL for a stored agreement PDF.

        `ownership-docs` is a public bucket, so this is a permanent public
        URL (no expiry). Returns None if the URL cannot be built.
        """
        try:
            url = (
                supabase_admin.storage.from_(self._bucket).get_public_url(path)
            )
            return url
        except Exception as exc:
            logger.error(f"[propflow] Failed to build public URL for {path}: {exc}")
            return None


# Singleton — same pattern as qwen_client.py and mem0_client.py
storage_client = SupabaseStorageClient()
